### ISSUE TITLE
Add "Type of Resource" to ETDs

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#488]
In order to facet everything on "Type of Resource", we need to update traject to parse character 6 from the leader in source MARC records.

The field labeled "Type of Resource" on index and show views is stored as work_type
https://github.com/curationexperts/alexandria-v2/blob/master/app/models/concerns/metadata.rb#L99

**Comment by mark-dce** [comment]
I will update this ticket with the field source and move the ticket to ready once Chrissy responds to [DIGREPO-458](https://help.library.ucsb.edu/browse/DIGREPO-458)

**Comment by mark-dce** [comment]
Use the file here for lookup values:
(this should probably be saved in config/authorities)

References:
http://www.loc.gov/marc/bibliographic/bdleader.html - for MARC type letters
http://www.loc.gov/standards/mods/v3/mods-userguide-elements.html#typeofresource - for Lables

**Comment by mark-dce** [comment]
**resource_types.yml**
```yaml
terms:
  - term: Text
    id: http://id.loc.gov/vocabulary/resourceTypes/txt
    marc6: ['a','t']
  - term: Cartographic Material
    id: http://id.loc.gov/vocabulary/resourceTypes/car
    marc6: ['e','f']
  - term: Notated Music
    id: http://id.loc.gov/vocabulary/resourceTypes/not
    marc6: ['c','d']
  - term: Sound Recording
    id: http://id.loc.gov/vocabulary/resourceTypes/aud
    marc6: ['i','j']
  - term: Still Image
    id: http://id.loc.gov/vocabulary/resourceTypes/img
    marc6: ['k']
  - term: Moving Image
    id: http://id.loc.gov/vocabulary/resourceTypes/mov
    marc6: ['g']
  - term: Three Dimensional
    id: http://id.loc.gov/vocabulary/resourceTypes/art
    marc6: ['r']
  - term: Multimedia
    id: http://id.loc.gov/vocabulary/resourceTypes/mul
    marc6: ['m']
  - term: Mixed Materials
    id: http://id.loc.gov/vocabulary/resourceTypes/mix
    marc6: ['p']
  - term: Collection
    id: http://id.loc.gov/vocabulary/resourceTypes/col
    marc6: 
```
