### ISSUE TITLE
Add controlled vocabulary for work_type ("Type of Resource")

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria-v2#497]
**resource_types.yml**
```yaml
terms:
  - term: Text
    id: http://id.loc.gov/vocabulary/resourceTypes/txt
    marc6: ['a','t']
  - term: Cartographic
    id: http://id.loc.gov/vocabulary/resourceTypes/car
    marc6: ['e','f']
  - term: Notated Music
    id: http://id.loc.gov/vocabulary/resourceTypes/not
    marc6: ['c','d']
  - term: Audio non-musical
    id: http://id.loc.gov/vocabulary/resourceTypes/aun
    marc6: ['i']
  - term: Audio musical
    id: http://id.loc.gov/vocabulary/resourceTypes/aum
    marc6: ['j']
  - term: Still image
    id: http://id.loc.gov/vocabulary/resourceTypes/img
    marc6: ['k']
  - term: Moving image
    id: http://id.loc.gov/vocabulary/resourceTypes/mov
    marc6: ['g']
  - term: Artifact
    id: http://id.loc.gov/vocabulary/resourceTypes/art
    marc6: ['r']
  - term: Multimedia
    id: http://id.loc.gov/vocabulary/resourceTypes/mul
    marc6: ['m']
  - term: Mixed material
    id: http://id.loc.gov/vocabulary/resourceTypes/mix
    marc6: ['p']
  - term: Collection
    id: http://id.loc.gov/vocabulary/resourceTypes/col
    marc6: 
```
