### ISSUE TITLE
Show page definition lists are under image

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria-v2#656]
See this page
http://ucsb.curationexperts.com/lib/ark:/48907/f3tm78bw

@dunn did one of the recent style changes affect this?

**Comment by jcoyne** [comment]
Compare to http://alexandria.ucsb.edu/lib/ark:/48907/f3tm78bw

**Comment by dunn** [comment]
I think this was happening before today's changes at least, but in any case the quickest fix should be
```css
.blacklight-catalog-show dl {
  clear: both;
}
```
